parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     zf2_cache_integration
    database_user:     tony
    database_password: tony

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            aksr89345nfk348957erj3485783fvs93e4rt
